<?php
/*
If you see this text in your browser, PHP is not configured correctly on this hosting provider.
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.2.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Заявка на фест',
	'heading' => 'Отправка новой формы',
	'success_redirect' => 'thanks.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'woops@i.ua',
		'to' => 'woops@i.ua'
	),
	'fields' => array(
		'custom_U950' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U944' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Сотовый телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сотовый телефон\' не может быть пустым.'
			)
		),
		'custom_U1052' => array(
			'order' => 3,
			'type' => 'radiogroup',
			'label' => 'Группа переключателей',
			'required' => true,
			'optionItems' => array(
				'Живое участие',
				'Доступ к онлайн трансляции',
				'Запись всех докладов'
			),
			'errors' => array(
				'required' => 'Поле \'Группа переключателей\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Группа переключателей\".'
			)
		)
	)
);

process_form($form);
?>
